### ISSUE TITLE
Auto-add node import to code samples if we detect a node import?

### ISSUE THREAD

**Issue by orta** [shikijs/twoslash#10]
E.g. `/// <reference types="node" />` to the Twoslash code ahead of time if we detect any known import for a node project?

Maybe too magical.

**Comment by orta** [comment]
Could we do something for both this and the react example? #20

**Comment by frencojobs** [comment]
I'm not sure about this one. Like, how would you properly detect node imports? For example, `fs`, `path` could as well be the user's absolute file paths when the user's on any other runtime instead of node, for example, `deno`. 

Otherwise, this could be easily implemented as how it's done with React. Right?

**Comment by orta** [comment]
We can use `ts. preProcessFile` to get a list of external modules - if that includes any of the known node ones ( which we can grab via  `require("module").builtinModules` - then the same concept can apply where we jam in `/// <reference types="node" />` at the top

**Comment by orta** [comment]
Think I've changed my mind on this - for the Jest website, I basically want to be able to be sure that "jest" is in types  for the TS compiler - the same thing should happen for node IMO.

**Comment by frencojobs** [comment]
Great! So no need for this feature, and a `compilerOptions > types > 'node'` would suffice?

**Comment by orta** [comment]
Yeah, we have `defaultCompilerOptions` in there already so I think this might just need documenting

**Comment by orta** [comment]
I think we recommend `types: node` somewhere
