### ISSUE TITLE
Better error messaging when Fenceparser throws

### ISSUE THREAD

**Issue by orta** [shikijs/twoslash#101]
Aye, but where?

<img width="477" alt="Screen Shot 2021-08-01 at 8 08 57 PM" src="https://user-images.githubusercontent.com/49038/127782622-0b384fd5-d4b1-4a83-b421-1194c3214201.png">

**Comment by orta** [comment]
<img width="458" alt="Screen Shot 2021-08-01 at 8 14 35 PM" src="https://user-images.githubusercontent.com/49038/127782747-0209a80a-245c-4949-a6ec-0e3848262819.png">

**Comment by frencojobs** [comment]
I'll make fenceparser throw with the index of the error within the meta string, but twoslash has to try-catch that and add a line number because fenceparser doesn't have the line number data.

**Comment by orta** [comment]
Yeah, I think it's definitely Twoslash's responsibility to show the error message via a try catch. It will have enough information to show the full fence meta on it's own too - so you might not need to do anything inside fenceparser
