### ISSUE TITLE
Add a cache-key with the '@typescript/twoslash' version into the cached JSON

### ISSUE THREAD

**Issue by semoal** [shikijs/twoslash#105]
👋  Hello Orta, passed some time without updating Docusaurus stuff, and today wanted to update the Rematch website.

After an update from `"docusaurus-preset-shiki-twoslash"` in 1.1.16 to 1.1.27, returned an error when starting the Docusaurus server.

```bash
TypeError: Cannot read property 'forEach' of undefined
    at Array.map (<anonymous>)
TypeError: Cannot read property 'forEach' of undefined
    at Array.map (<anonymous>)
TypeError: Cannot read property 'forEach' of undefined
    at Array.map (<anonymous>)
TypeError: Cannot read property 'forEach' of undefined
    at Array.map (<anonymous>)
TypeError: Cannot read property 'forEach' of undefined
    at Array.map (<anonymous>)
TypeError: Cannot read property 'forEach' of undefined
    at Array.map (<anonymous>)
```

After some digging in the source code I found:
https://github.com/shikijs/twoslash/blob/main/packages/shiki-twoslash/src/renderers/twoslash.ts#L246
```js
function groupBy(list, keyGetter) {
  var map = new Map();
  list.forEach(function (item) {
```

This function iterates over these properties:

```js
  var errorsGroupedByLine = groupBy(twoslash.errors, function (e) {

  var staticQuickInfosGroupedByLine = groupBy(twoslash.staticQuickInfos, function (q) {

  var queriesGroupedByLine = groupBy(twoslash.queries, function (q) {

  var tagsGroupedByLine = groupBy(twoslash.tags, function (q) {

```

`twoslash.tags` makes the groupBy function crashing because its undefined.

I can open a pull request checking inside groupBy by undefined, if its undefined we do an early return of the map. 

Wanted to open the issue, just for confirming this is an issue itself, and also to confirme that tags as undefined is something usual that should be checked (or is someting bad in our docs).

Cheers

**Comment by semoal** [comment]
Yep, found the real problem mate.

Basically `cachedTwoSlash` creates a node_modules/.cache, I had some cached files there of previous builds that made tags undefined.

After deleting the .cache/twoslash, everything worked fine again.

Probably adding a cache key related to the current package version could be nice.

**Comment by orta** [comment]
Agree!
