### ISSUE TITLE
`remark-shiki-twoslash` inside workspace package incorrectly resolves dependencies

### ISSUE THREAD

**Issue by vlad-zhukov** [shikijs/twoslash#127]
When using `remark-shiki-twoslash` inside workspace package, it either doesn't resolve dependencies at all or even uses wrong versions. It took me quite some time to debug that `remark-shiki-twoslash` [sets `vfsRoot` to  basically `/node_modules/remark-shiki-twoslash/`](https://github.com/shikijs/twoslash/blob/fbf061261fcda90c46e946ce1e2e9357d465c145/packages/remark-shiki-twoslash/src/index.ts#L107), rather than `twoslash`\`s advertised ` process.cwd()`, which in turn makes TypeScript resolve packages from root rather than current package directory.

The userland fix for this is to set `vfsRoot: process.cwd()`.

But why does it work this way? And can we change it to use the default behaviour?

P.S. Thanks for you work!

**Comment by orta** [comment]
I feel like I had problems with `cwd` but I agree that it's probably the right thing to do, want to try send a PR and we'll see how the tests turn out?
