### ISSUE TITLE
Cache folder is created as sibling of node_modules

### ISSUE THREAD

**Issue by tmair** [shikijs/twoslash#130]
It seems that the intention is to have the `.cache/twoslash` directory inside the `node_modules` directory (https://github.com/shikijs/twoslash/issues/105#issuecomment-897422052). The cache is however created as as sibling of the `node_modules` directory.

If the intention is to create the cache as a sibling of `node_modules` feel free to close the issue. Otherwise I could send a PR if this should be addressed.

**Comment by orta** [comment]
Nope, ideally it should always live inside `node_modules`
