### ISSUE TITLE
docusaurus-preset: support module shorthands

### ISSUE THREAD

**Issue by Josh-Cena** [shikijs/twoslash#137]
Docusaurus now supports [module shorthands](https://docusaurus.io/docs/using-plugins#module-shorthands), similar to ESLint and Babel config.

This means `@docusaurus/preset-classic` may instead be simply referred to as `classic` in the config, which currently panics with "Couldn't find a preset or a plugin supported by twoslash".

We can probably expose a utility function in Docusaurus that the shiki preset can use to resolve module shorthands to their full names/paths?

**Comment by orta** [comment]
Our lookup code is pretty simple: https://github.com/shikijs/twoslash/blob/a9a4d815c46ed9cb0ebfcd69a25af4c1d1ff4bc5/packages/docusaurus-preset-shiki-twoslash/index.js#L23-L28

I think adding the shorthands to the list is fine
