### ISSUE TITLE
docusaurus-preset-shiki-twoslash documentation's setup step 4 should not be required

### ISSUE THREAD

**Issue by frencojobs** [shikijs/twoslash#17]
I just noticed that the preset has already injected the required hover events here.
https://github.com/shikijs/twoslash/blob/7183139801e39d55d4688fa3c860c47c771ac1df/packages/docusaurus-preset-shiki-twoslash/shiki-twoslash-theme/index.js#L9-L90

So, technically the step 4 of the setup in README should not be required right?
![step4](https://user-images.githubusercontent.com/17830687/121842352-4b320800-cd06-11eb-95f8-d69635d764e7.png)

**P.S.** On one particular incident (that I had last night but I can't reproduce again) the popups are doubled.

**P.S.** Also step 4 only works when I don't install `shiki-twoslash` as a separate dependency. When installed as a dependency, docusaurus can't resolve the package and panic. (this is reproducible)

**Comment by orta** [comment]
The need for JS got dropped a while back, perhaps this didn't get a release update?

**Comment by orta** [comment]
I've forced a deploy of the plugin: https://github.com/shikijs/twoslash/commit/92f7930b76f5347cdc534858db249c7fb3cf9be1

**Comment by frencojobs** [comment]
Closing this as it is fixed.
