### ISSUE TITLE
Characters are encoded as HTML entities

### ISSUE THREAD

**Issue by frencojobs** [shikijs/twoslash#18]
Characters such as `<` and `"` are encoded as HTML character entities. This behavior can be reproduced by following the `docusaurus-preset-shiki-twoslash`'s setup guide on a plain docusaurus template. Weirdly `>` is not replaced with `&gt;`.

![entities](https://user-images.githubusercontent.com/17830687/121843219-da8beb00-cd07-11eb-98ab-31d157ac329a.png)

**Comment by orta** [comment]
This is likely from a bad deploy of the docusaurus plugin (.e.g the JS isn't prepared for this but the CSS should be fine )

**Comment by frencojobs** [comment]
Closing this as it is fixed.
