### ISSUE TITLE
JSX codes are not highlighted

### ISSUE THREAD

**Issue by frencojobs** [shikijs/twoslash#19]
Followed as guided with the latest docusaurus plugin, and I saw that non-ts code blocks are not highlighted. Have tested and can confirm that this is reproducible in multiple projects.

![nonts](https://user-images.githubusercontent.com/17830687/122157389-c4f5fd00-ce90-11eb-9d2e-6d135589d92c.png)

**Comment by orta** [comment]
Looks specific to JSX, perhaps shiki doesn't recognize the identifier and we need to switch it to 'js' ahead of time.

![Screen Shot 2021-06-16 at 12 36 37 PM](https://user-images.githubusercontent.com/49038/122212239-8451b000-ce9f-11eb-9bf3-cf87091f44c1.png)

**Comment by frencojobs** [comment]
Fixed by #32.
