### ISSUE TITLE
Allow implicit React import?

### ISSUE THREAD

**Issue by frencojobs** [shikijs/twoslash#20]
Since [JSX-Transform](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html), I have not used to importing React explicitly in my codebases. I want to treat the same with my code blocks i.e. I want to configure so that React is imported implicitly in my `tsx` code blocks.

![errrrrr](https://user-images.githubusercontent.com/17830687/122158825-43ec3500-ce93-11eb-879f-bf3203ad2dab.png)

Currently, I think best I can do is to cut imports like,

```tsx
import React from 'react'
// ---cut---
```

But I don't think it's the best option. Or am I missing something?

**Comment by orta** [comment]
Interesting question, you could add `// @allowUmdGlobalAccess` to skip the error and _not_ require the cut. 

Given that this is likely to be something a bunch of people hit, I think it makes sense for us to have a default on `tsx twoslash` to automatically add React in shiki-twoslash, and to have an config option to disable that behavior

**Comment by frencojobs** [comment]
Hey, @orta I think you mistook this with #19 and closed this. I'll close #19. Can you reopen this one?

**Comment by frencojobs** [comment]
Hi @orta, do you have any idea in mind of how this feature could be implemented? I would love to help code this if I have at least a rough path to do so. Thanks.

**Comment by frencojobs** [comment]
Gotcha! So, we'll leave the need to have, for example "@types/react" here, as a dependency as the user's full responsibility then?

**Comment by orta** [comment]
Yes, IMO

**Comment by frencojobs** [comment]
![2021-06-24_09-56](https://user-images.githubusercontent.com/17830687/123198092-8be20c00-d4d2-11eb-9922-e5954bf3e1a5.png)

Inlining `\\ ---cut---` already works. So all that's left to do is to add the line if the file extension is either `tsx` or `jsx` like this.

![codde](https://user-images.githubusercontent.com/17830687/123199925-d31dcc00-d4d5-11eb-8a4e-06f9efb3a8dd.png)

_Of course, we need to add an option of enable/disable this and check that value first._

How do you think?

**Comment by frencojobs** [comment]
Oh sorry, I understand what you meant. The `\\ ---cut---` only works once in a block. Then yes, we have to add a new inline cut option, because otherwise, it brokes twoslash.

**Comment by frencojobs** [comment]
Hi @orta, I implemented a less busier solution by combining all the cuts before passing the code to `twoslasher`. Because otherwise, to implement inline cut comments requires the need to shift the metadata positions after cutting all theese lines, which I think is overkill just for this feature.
