### ISSUE TITLE
Type definitions are not properly aligned

### ISSUE THREAD

**Issue by frencojobs** [shikijs/twoslash#21]
I'm probably opening too many issues, but hey I hope these help.

The type definitions are not properly aligned as shown here with extra multiple spaces.

![idkthis](https://user-images.githubusercontent.com/17830687/122200907-7d3b9980-cec1-11eb-99dc-8eb5f3170af4.png)

I'm guessing this is because of the `lsp` attribute not being able to hold line break information present in the type definition because it usually doesn't happen in some long strings. I'm not so sure but I think it could be fixed by replacing the `\n` with `&#10;` before putting them in the attribute.

**Comment by orta** [comment]
Agree, probably just a text transform somewhere
