### ISSUE TITLE
Add a CONTRIBUTING.md

### ISSUE THREAD

**Issue by frencojobs** [shikijs/twoslash#29]
The title is self-explanatory.

It will be good to have that for new contributors. I'm also having a little difficulty testing the examples. The examples are downloading `shiki-twoslash` from npm instead of linking to the updated `packages/shiki-twoslash`. So I'm not sure whether my changes are actually working or not.

**Comment by orta** [comment]
There's a better one now, it's not complete because I've not made my decisions on how to handle the examples yet

**Comment by orta** [comment]
I think this is good enough now
