### ISSUE TITLE
Site is still not updated?

### ISSUE THREAD

**Issue by frencojobs** [shikijs/twoslash#37]
I think with the latest fix, `twoslash-cli` should be formatting the snippets correctly for newlines. I have even tested that with #36 but the examples in the site are still not yet updated. 

![image](https://user-images.githubusercontent.com/17830687/122520599-d0d0f300-d039-11eb-8539-9913d663431b.jpeg)

I tried updating the site's `twoslash-cli` dependency to `^1.2.0` locally, but it's still not working so I did not submit a PR. Can you check it if you have time? Thanks.

**Comment by orta** [comment]
The version param wouldn't update to `1.2.x` automatically via `yarn upgrade twoslash-cli` on the deploy pipeline, it should now

**Comment by frencojobs** [comment]
Hey, @orta it is still not updated. I think I know why.

Compare the `twoslash-cli`'s v1.2.0 [package.json](https://github.com/shikijs/twoslash/blob/69c799ce5ee0a7a93a409f393dbb51280278aed8/packages/twoslash-cli/package.json) with [what's on npm](https://cdn.jsdelivr.net/npm/twoslash-cli@1.2.0/package.json) using jsdelivr. You can see even though the version's updated to `v1.2.0`, the `shiki-twoslash` package version is still not updated which is why the site's generated examples are not yet updated.

I'm not sure what happened during deployment. Is it up to NPM or CI deploy step?

**Comment by orta** [comment]
Bah
