### ISSUE TITLE
How to enable top level await?

### ISSUE THREAD

**Issue by frencojobs** [shikijs/twoslash#47]
Since the error says I have to use `module: esnext` to get top-level await working, I modified my config to be like this.

```js
[
  "docusaurus-preset-shiki-twoslash",
  {
    themes: ["min-light", "min-dark"],
    defaultCompilerOptions: {
      module: "ESNext",
      types: ["node"],
    },
  },
],
```

But it still doesn't work. The `types: ["node"]` line helps with node imports, but the `module` line is not working at all?

**Comment by frencojobs** [comment]
Oh no. I'm just stupid, I need to add `target` option with a higher one. Sorry.

**Comment by frencojobs** [comment]
P.S. I ended up inlining these options into code blocks since `defaultCompilerOptions` is weirdly not working for me.
```ts
// @module: ESNext
// @target: ESNext
```

**Comment by orta** [comment]
I need to explore `defaultCompilerOptions` for the jest website, so will verify that bug when I get ther

**Comment by orta** [comment]
I think `defaultCompilerOptions` is 👍🏻
