### ISSUE TITLE
Support for module declarations

### ISSUE THREAD

**Issue by frencojobs** [shikijs/twoslash#48]
Since example code blocks usually import imaginary files as an example, twoslash will throw if the files are not found and it is not optimal. One way I can think of to fix this behavior is to allow the author to stuff module declarations inside code blocks??

```ts twoslash
declare module "foo-module" {
  function foo(): void; 
  export = foo;
}
// ---d.ts---
import * as foo from "foo-module";
foo();
```

**Comment by orta** [comment]
No need for unique syntax - this is supported out of the box by the existing multi-file syntax:

````
```ts twoslash
// @filename: node_modules/foo-module/index.d.ts
export function foo(str: string): void; 
  
// @filename: index.ts
// ---cut---
import {foo} from "foo-module";
foo(123);
//^?
```
````

https://www.typescriptlang.org/dev/bug-workbench/?#code/PTAEAEDMEsBsFMB2BDAtvAXKRB7AJvAPqr4CuCAzsJDjgLQl7nzDSIEAeAdHlwC4UAsACgRoUPA4AHHACc+oSKUQBjPtByJFtABQBKLADcc0PAG5QYidLkKCkZOQU0cVkSAgwEKdFjacuACshYWhUGXlQACpQZAptHEVZHFRQACIXBjIENLMRF3084RAAPQB+IA

**Comment by frencojobs** [comment]
Ooh love it.
