### ISSUE TITLE
markdown-it-shiki-twoslash needs adjustments to publish as a module

### ISSUE THREAD

**Issue by DanielRosenwasser** [shikijs/twoslash#55]
There's a few issues with the way the markdown-it package is published:

1. It ships `.js` files with `import`s - the `package.json` needs to specify `"type": "module"` if it wants to do that.
2. The package `import`s a non-module package (`deasync`). It probably needs to switch to `require` to bring it in. As a result, I'm not sure if #54 will even work.

**Comment by frencojobs** [comment]
You're right, it has the "module" field specified but the `.esm.js` wasn't generated. It used to be generated but since shifting to `esbuild`, it has not been properly worked on.

**Comment by orta** [comment]
Ah, this is unintentional - rebuild doesn't switch `import` to `require` which makes sense. I think we should probably just ship as a module and see how it goes.
