### ISSUE TITLE
Docusaurus preset’s README code sample are deformed

### ISSUE THREAD

**Issue by frencojobs** [shikijs/twoslash#60]
GitHub

![image](https://user-images.githubusercontent.com/17830687/124372148-a2484e80-dcae-11eb-8eff-f3647ba7c92a.jpeg)

NPM

![image](https://user-images.githubusercontent.com/17830687/124372162-c572fe00-dcae-11eb-85b2-d0171325230f.jpeg)

**Comment by orta** [comment]
boo
