### ISSUE TITLE
Selecting, copying and pasting popovers and completions includes an extra newline

### ISSUE THREAD

**Issue by benlesh** [shikijs/twoslash#67]
Similar to the issue reported in #65, but not *exactly* the same...

When using queries and completions, it's fairly easy to prevent the user from selecting and copying the popovers or completions with a little CSS. Something like:

```css
.popover-prefix, .popover, .query, .inline-completions {
  user-select: none;
}
```

This is, of course, behavior that should be _totally_ optional, because who knows? Maybe authors want people to be able to copy and paste that. Either way. The issue becomes [this line here, where an `\n` is used](https://github.com/shikijs/twoslash/blob/97639be0eaab5259182d37c4e83f75344ac21282/packages/shiki-twoslash/src/renderers/twoslash.ts#L191)

Basically, there's no way to prevent the user from selecting that extra newline because it's an `\n` and not contained in a `<div>` of some sort. I'd recommend not using `<div class="line">` from [the `prefix` variable](https://github.com/shikijs/twoslash/blob/97639be0eaab5259182d37c4e83f75344ac21282/packages/shiki-twoslash/src/renderers/twoslash.ts#L60), because that is something people can leverage to generate line numbers for just code lines (as outlined in #65), rather maybe a new prefix type like `<div class="meta-line">` or something like that? 

The catch here is I think documentation/styling may need to be updated? A div will, of course, cause the new line behavior, so maybe not.

**source**
![image](https://user-images.githubusercontent.com/1540597/124826020-fa46b580-df39-11eb-82e3-1b58f5fbdffe.png)

**browser (selecting)**
![image](https://user-images.githubusercontent.com/1540597/124825982-ebf89980-df39-11eb-9768-11b363d4c137.png)

**pasted**
![image](https://user-images.githubusercontent.com/1540597/124826091-0e8ab280-df3a-11eb-9044-40b2d2c010be.png)

**Comment by benlesh** [comment]
I just confirmed locally that the suggested solution does work, and doesn't seem to have any impact on the layout:

**browser (selected)**
![image](https://user-images.githubusercontent.com/1540597/124826456-7c36de80-df3a-11eb-92e9-847518a3d553.png)

**pasted**
![image](https://user-images.githubusercontent.com/1540597/124826530-8e188180-df3a-11eb-9185-3cea9aae8c75.png)

**Comment by orta** [comment]
Yeah, I agree - unless you've started a PR I'll do it now as I've got the stuff open
