### ISSUE TITLE
Hidden code blocks create <undefined/> in docusaurus

### ISSUE THREAD

**Issue by 3Shain** [shikijs/twoslash#73]
````·md
```twoslash include main
// some code
```
````
becomes
```html
<undefined></undefined>
```
in docusaurus (version 2.0.0-beta.3)

**Comment by frencojobs** [comment]
Thanks for the report, a fix is on the way.

**Comment by OliverJAsh** [comment]
I'm still running into this issue, running all of the latest versions. It looks like the fix in https://github.com/shikijs/twoslash/pull/74 would only help when `wrapFragments` is set to `true`?
