### ISSUE TITLE
frencojobs is now an admin

### ISSUE THREAD

**Issue by orta** [shikijs/twoslash#80]
Congrats! 

I figure you've been contributing regularly and doing a great job. This change gives you write access (which also gives you deploy access, as we deploy from CI) - feel free to self merge and deploy small features/bugs (run `pnpm deploy` from main locally) but anything chunky I should probably at least take PR review like we're doing today

**Comment by frencojobs** [comment]
Oo thanks, man. Much much appreciated. I'll try my best to manage tiny things myself, and will request review/help from you occasionally on other PRs.

**Comment by 728755225** [comment]
> 
Duplicate of #

**Comment by orta** [comment]
Right?

**Comment by frencojobs** [comment]
Haha, is that a bot? Malfunctioning??

**Comment by orta** [comment]
Yeah, think so - when you hover the account above it says "Facebook Forgot password" in czech
