### ISSUE TITLE
11ty's integration is not working.

### ISSUE THREAD

**Issue by pouyakary** [shikijs/twoslash#87]
Hey there ! I wanted to build something with twoslash and it seems that I have the setup right:

<img width="958" alt="Screen Shot 1400-05-03 at 22 33 32" src="https://user-images.githubusercontent.com/2157285/126908795-2117dd4a-5258-474e-a886-1f775e95548c.png">

And a simple test case like this:

<img width="578" alt="Screen Shot 1400-05-03 at 22 36 35" src="https://user-images.githubusercontent.com/2157285/126908856-02076b9e-8945-4f43-8b82-0df5952c0dce.png">

Actually turns into this; there is Shiki working but not the twoslash.

<img width="1440" alt="Screen Shot 1400-05-03 at 22 35 53" src="https://user-images.githubusercontent.com/2157285/126908839-86e028da-9b57-448b-89ca-a4350128c158.png">

_P.S. I don't know what to add more than what is mentioned in the guide so I don't know if it is my problem or the package is not working_

**Comment by orta** [comment]
I think it might only be working in canary builds, as that's what I tested it against: https://github.com/shikijs/twoslash/blob/main/examples/eleventy/package.json#L6

**Comment by orta** [comment]
oh, hrm, interesting let me verify the twoslashiness!

**Comment by pouyakary** [comment]
Haha! man you are fast! thanks a lot, I'm looking forward to hearing from you :)

**Comment by orta** [comment]
Main branch looks good in our example, is it possible you've not included the CSS?

**Comment by pouyakary** [comment]
Okay let me test!

**Comment by pouyakary** [comment]
So it worked but still the `ts` on top is visible and the docs are generated but not interactive. I'm guessing that it is left to the developer to implement, but are there any implementations? or as you mentioned, an includable CSS template?

<img width="1440" alt="Screen Shot 1400-05-03 at 22 56 21" src="https://user-images.githubusercontent.com/2157285/126909388-9686b181-7c0f-47d3-8957-61eef009bdb4.png">

**Comment by pouyakary** [comment]
P.S. As you can tell, I wanna load up the Pro Colors into it. How do you add a Shiki theme outside of what is supported?

**Comment by orta** [comment]
( added some docs on getting the theme, going to be off the computer for a while so won't be able to dig into the twoslash code fence not being picked up issue: https://github.com/shikijs/twoslash/commit/6987d158d548b38d1ac5c7927db8162e4788eb2a )

**Comment by pouyakary** [comment]
@orta all fixed and working :) thanks a lot for the help and the amazing tool 👍🏻

**Comment by frencojobs** [comment]
> So it worked but still the `ts` on top is visible and the docs are generated but not interactive. I'm guessing that it is left to the developer to implement, but are there any implementations? or as you mentioned, an includable CSS template?

The README on https://www.npmjs.com/package/remark-shiki-twoslash contains CSS used on TypeScript website. https://github.com/shikijs/twoslash/blob/6987d158d548b38d1ac5c7927db8162e4788eb2a/packages/docusaurus-preset-shiki-twoslash/docusaurus-theme-shiki-twoslash/theme/CodeBlock/styles.css is Docusaurus ready theme with Infima. You can reference them to write yourself one or tweak them according to your preference.

**Comment by pouyakary** [comment]
@frencojobs Thanks a lot ♥️
